import React from "react";
import ReactDOM from "react-dom/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Cr from "../pages/conditionalRendering/cr.js";
import PropsChallenges from "./start/props-challenges.js";
//import ListsProject from "../pages/reactMockup/RenderingListsProject.js";
import RenderingLists from "./renderingLists/renderingLists.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RenderingLists />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
